apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis-cluster
  labels:
    app: redis-cluster
spec:
  ports:
  - name: redis-port
    protocol: "TCP"
    port: 6379
    targetPort: 6379
  - name: cluster-port
    protocol: "TCP"
    port: 16379
    targetPort: 16379
  selector:
    app: redis-cluster